version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:
  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    env_file:
      - ./.env
    networks:
      default:
      reaction:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: