version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:

  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command: migrate sql -e -y
    depends_on:
      - postgres
    networks:
      default:
      reaction:
    env_file: "./reaction-hydra/.env.example"
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.0.8
    command: serve all --dangerous-force-http
    depends_on:
      - postgres
      - hydra-migrate
    networks:
      default:
      reaction:
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    env_file: "./reaction-hydra/.env.example"
    restart: unless-stopped

  postgres:
    image: postgres:10.3
    env_file:
      - ./.env.example
    networks:
      default:
      reaction:
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./reaction
      dockerfile: Dockerfile
    depends_on:
      - identity
    image: reaction-api
    env_file:
      - ./reaction/.env.example
    networks:
      default:
      reaction:
    ports:
      - "3000:3000"

  identity:
    build:
      context: ./reaction-identity
      dockerfile: Dockerfile
    depends_on:
      - hydra
    image: reaction-identity
    env_file:
      - ./reaction-identity/.env.example
    networks:
      default:
      reaction:
    ports:
      - "4100:4100"

  reaction-admin:
    build:
      context: ./reaction-admin
      dockerfile: Dockerfile
    depends_on:
      - identity
    image: reaction-admin
    env_file:
      - ./reaction-admin/.env.example
    networks:
      default:
      reaction:
    ports:
      - "4080:4080"
      - "9231:9229"

volumes:
  postgres-data:
