version: '3.4'

networks:
  reaction:
    external:
      name: reaction.localhost

services:

  hydra-migrate:
    image: oryd/hydra:v1.0.8
    command: migrate sql -e -y
    depends_on:
      - postgres
    networks:
      default:
      reaction:
    env_file: "./reaction-hydra/.env"
    restart: on-failure

  hydra:
    image: oryd/hydra:v1.0.8
    command: serve all --dangerous-force-http
    depends_on:
      - hydra-migrate
      - postgres
    networks:
      default:
      reaction:
    ports:
      # Public port
      - "4444:4444"
      # Admin port
      - "4445:4445"
      # Port for hydra token user
      - "5555:5555"
    env_file: "./reaction-hydra/.env"
    restart: unless-stopped

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=hydra
    networks:
      default:
      reaction:
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    build:
      context: ./reaction
      dockerfile: Dockerfile
    image: reaction-api
    depends_on:
      - mongo
    env_file:
      - ./reaction/.env
    networks:
      default:
      reaction:
    ports:
      - "3000:3000"

  mongo:
    image: mongo:4.2.0
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    networks:
      default:
      reaction:
    ports:
      - "27017:27017"
    volumes:
      - mongo-db4:/data/db

  identity:
    build:
      context: ./reaction-identity
      dockerfile: Dockerfile
    image: reaction-identity
    env_file:
      - ./reaction-identity/.env
    networks:
      default:
      reaction:
    ports:
      - "4100:4100"

  reaction-admin:
    build:
      context: ./reaction-admin
      dockerfile: Dockerfile
    image: reaction-admin
    env_file:
      - ./reaction-admin/.env
    networks:
      default:
      reaction:
    ports:
      - "4080:4080"
      - "9231:9229"

volumes:
  postgres-data:
  mongo-db4:
